openapi: 3.0.0
info:
  title: Спецификация для сервиса аунтификации пользователей
  version: 1.0.0
paths:
  /users/register:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:
          description: Регистрация прошла успешно!
        400:
          description: В процессе регистрации произошла ошибка
          content:
            application/json:
              schema:
                type: string
  /users/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        200:



components:
  schemas:
    User:
      description: В скором времени будет заменент DTO, где не будет id объекта
      type: object
      properties:
        id:
          description: Можно бросать любой, так как он автоматически сгенерируется системой
          type: number
          format: long
        name:
          type: string
        email:
          type: string
        hashedPassword:
          type: string
          description: Должен быть в зашифрованном виде, в идеале в формате md5
        isOrganization:
          description: Является ли данный пользователь представителем организации?
          type: boolean

